networks:
  sas-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  auth-server:
    container_name: auth-server
    build: ./spring-authorization-server
    ports:
      - 9000:9000
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9000/.well-known/openid-configuration" ]
      start_period: 2s
      start_interval: 1s
      retries: 3
      timeout: 1s
    networks:
      sas-network:

  resource-server:
    container_name: resource-server
    build: ./resource-server
    ports:
      - 8090:8090
    depends_on:
      auth-server:
        condition: service_healthy
    networks:
      sas-network:

  client-server:
    container_name: client-server
    build: ./client-server
    ports:
      - 8080:8080
    depends_on:
      auth-server:
        condition: service_healthy
    networks:
      sas-network: